# Form implementation generated from reading ui file 'ui_error_on_commit.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_error_while_commiting(object):
    def setupUi(self, error_while_commiting):
        error_while_commiting.setObjectName("error_while_commiting")
        error_while_commiting.resize(899, 635)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("croco_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        error_while_commiting.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(error_while_commiting)
        self.label.setGeometry(QtCore.QRect(90, -10, 681, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.error_log = QtWidgets.QLabel(error_while_commiting)
        self.error_log.setGeometry(QtCore.QRect(50, 80, 751, 531))
        self.error_log.setAcceptDrops(True)
        self.error_log.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.error_log.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.error_log.setObjectName("error_log")

        self.retranslateUi(error_while_commiting)
        QtCore.QMetaObject.connectSlotsByName(error_while_commiting)

    def retranslateUi(self, error_while_commiting):
        _translate = QtCore.QCoreApplication.translate
        error_while_commiting.setWindowTitle(_translate("error_while_commiting", "AN ERROR OCCURED"))
        self.label.setText(_translate("error_while_commiting", "Following problem occured while commiting:"))
        self.error_log.setText(_translate("error_while_commiting", "TextLabel"))
