# Form implementation generated from reading ui file 'ui_confirmation_window.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_confirmation_window(object):
    def setupUi(self, confirmation_window):
        confirmation_window.setObjectName("confirmation_window")
        confirmation_window.resize(668, 585)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("croco_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        confirmation_window.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(confirmation_window)
        self.label.setGeometry(QtCore.QRect(70, 10, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.markup_displayer = QtWidgets.QLabel(confirmation_window)
        self.markup_displayer.setGeometry(QtCore.QRect(30, 70, 271, 421))
        self.markup_displayer.setText("")
        self.markup_displayer.setObjectName("markup_displayer")
        self.commit_button = QtWidgets.QPushButton(confirmation_window)
        self.commit_button.setGeometry(QtCore.QRect(450, 140, 111, 41))
        self.commit_button.setObjectName("commit_button")
        self.redo_button = QtWidgets.QPushButton(confirmation_window)
        self.redo_button.setGeometry(QtCore.QRect(450, 230, 111, 41))
        self.redo_button.setObjectName("redo_button")

        self.retranslateUi(confirmation_window)
        QtCore.QMetaObject.connectSlotsByName(confirmation_window)

    def retranslateUi(self, confirmation_window):
        _translate = QtCore.QCoreApplication.translate
        confirmation_window.setWindowTitle(_translate("confirmation_window", "Confirmation_window"))
        self.label.setText(_translate("confirmation_window", "Please confirm entered markup"))
        self.commit_button.setText(_translate("confirmation_window", "Commit!"))
        self.redo_button.setText(_translate("confirmation_window", "Redo"))
