# Form implementation generated from reading ui file 'ui_successful_commit.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_success_window(object):
    def setupUi(self, success_window):
        success_window.setObjectName("success_window")
        success_window.resize(1080, 486)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("croco_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        success_window.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(success_window)
        self.label.setGeometry(QtCore.QRect(100, 10, 891, 201))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.close_window = QtWidgets.QPushButton(success_window)
        self.close_window.setGeometry(QtCore.QRect(230, 220, 561, 231))
        self.close_window.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sawasdee")
        font.setPointSize(29)
        self.close_window.setFont(font)
        self.close_window.setObjectName("close_window")

        self.retranslateUi(success_window)
        QtCore.QMetaObject.connectSlotsByName(success_window)

    def retranslateUi(self, success_window):
        _translate = QtCore.QCoreApplication.translate
        success_window.setWindowTitle(_translate("success_window", "SUCCESSFULLY COMMITED!"))
        self.label.setText(_translate("success_window", "MARKUP HAS BEEN SUCCESSFULLY COMMITED!"))
        self.close_window.setText(_translate("success_window", "Close window"))
